default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: '123456'
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>  # Default PostgreSQL port

development:
  <<: *default
  database: crud_dock_development

test:
  <<: *default
  database: crud_dock_test

production:
  <<: *default
  database: crud_dock_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
